table:
  database: testDb

kafka:
  topic:
    - t_1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
    - topic1#topic2#table
