table:
  database:  orcl
  owner:
    - DDS
#    - DBMGR

kafka:
  bootstrap: 172.20.3.227:9092

oracle:
  url: jdbc:oracle:thin:@172.20.3.225:1521:orcl
  username: dbmgr
  password: oracle

hadoop:
  hiveUri: thrift://172.20.29.46:9083
  warehouse: hdfs://172.20.29.46:8020/user/hive/warehouse/
  hiveConfDir: /etc/hive/conf.cloudera.hive/
  hadoopConfDir: /etc/hadoop/conf.cloudera.yarn/

#
#  //        String hiveUri = "thrift://172.20.29.46:9083";
#  //        String warehouse = "hdfs://172.20.29.46:8020/user/hive/warehouse/";
#  //        String hiveConfDir = "/etc/hive/conf.cloudera.hive/";
#  //        String hadoopConfDir = "/etc/hadoop/conf.cloudera.yarn/";
#  //        String hiveConfDir = "D:\\workspace\\iceberg-demo\\config\\hive-conf-46";
#  //        String hadoopConfDir = "D:\\workspace\\iceberg-demo\\config\\hive-conf-46";
#  //        String hiveUri = "thrift://172.20.1.34:9083";
#  //        String warehouse = "hdfs://172.20.1.34:8020/user/hive/warehouse/";
#  //        String hiveConfDir = "D:\\workspace\\iceberg-demo\\config\\hive-conf-34";
#  //        String hadoopConfDir = "D:\\workspace\\iceberg-demo\\config\\hive-conf-34";